[package]
name = "tronk"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.29.1"
eframe = "0.29.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1.10.2"
uuid = { version = "1.6.1", features = ["v4", "serde"] }

    